export * from '../types/map/styles';
import {MapTheme} from '../types/map/styles';

const mergeIntoDefault = (style: MapTheme) => Object.assign({}, Plain, style);

export const Plain: MapTheme = {
    className: 'plain',
    containerBackground: 'white',
    fontFamily: '"Helvetica Neue",Helvetica,Arial,sans-serif',
    fontSize: '13px',
    stroke: 'black',
    pipelineArrowStroke: 'black',
    evolutionSeparationStroke: 'black',
    mapGridTextColor: 'black',
    pipelineArrowHeight: 5,
    pipelineArrowWidth: 5,
    strokeWidth: 1,
    strokeDasharray: '2,2',
    anchor: {
        fontSize: '14px',
    },
    attitudes: {
        strokeWidth: '5px',
        fontSize: '14px',
        pioneers: {
            stroke: '#3490dd',
            fill: '#3ccaf8',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        settlers: {
            stroke: '#396dc0',
            fill: '#599afa',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        townplanners: {
            stroke: '#4768c8',
            fill: '#936ff9',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
    },
    methods: {
        buy: {
            stroke: '#D6D6D6',
            fill: '#AAA5A9',
        },
        build: {
            stroke: '#000000',
            fill: '#D6D6D6',
        },
        outsource: {
            stroke: '#444444',
            fill: '#444444',
        },
    },
    market: {
        stroke: 'red',
        fill: 'white',
    },
    component: {
        fill: 'white',
        stroke: 'black',
        evolved: 'red',
        evolvedFill: 'white',
        strokeWidth: 1,
        pipelineStrokeWidth: 1,
        radius: 5,
        textColor: 'black',
        textOffset: 8,
        evolvedTextColor: 'red',
        fontSize: '14px',
        fontWeight: '500',
    },
    submap: {
        fontSize: '13px',
        fill: 'black',
        stroke: 'black',
        evolved: 'red',
        evolvedFill: 'black',
        strokeWidth: 1,
        pipelineStrokeWidth: 1,
        radius: 5,
        textColor: 'black',
        textOffset: 8,
        evolvedTextColor: 'red',
    },
    link: {
        stroke: 'grey',
        strokeWidth: 1,
        evolvedStroke: 'red',
        evolvedStrokeWidth: 1,
        flow: '#99c5ee9e',
        flowStrokeWidth: 10,
        flowText: '#03a9f4',
        contextFontSize: '11px',
    },
    fluidLink: {
        stroke: 'grey',
        strokeDasharray: '2,2',
        strokeWidth: 2,
    },
    annotation: {
        stroke: '#595959',
        strokeWidth: 2,
        fill: 'white',
        text: 'black',
        boxStroke: '#595959',
        boxStrokeWidth: 1,
        boxFill: '#FFFFFF',
        boxTextColour: 'black',
    },
    note: {
        fontWeight: 'bold',
        fontSize: '12px',
        fill: 'black',
        textColor: 'black',
        evolvedTextColor: 'red',
    },
};

export const Handwritten = mergeIntoDefault({
    className: 'handwritten',
    fontFamily: '"Gloria Hallelujah", cursive',
    stroke: 'black',
    pipelineArrowStroke: 'black',
    evolutionSeparationStroke: 'black',
    component: {
        fill: 'white',
        stroke: 'black',
        evolved: 'red',
        evolvedFill: 'white',
        strokeWidth: 1,
        pipelineStrokeWidth: 1,
        radius: 5,
        evolvedTextColor: 'red',
        textColor: 'black',
        fontWeight: '500',
        fontSize: '12px',
    },
    annotation: {
        stroke: '#595959',
        strokeWidth: 2,
        boxStroke: '#595959',
        boxStrokeWidth: 1,
        boxFill: '#FFFFFF',
        boxTextColour: 'black',
        fill: '',
        text: '',
    },
    methods: {
        buy: {
            stroke: '#D6D6D6',
            fill: '#AAA5A9',
        },
        build: {
            stroke: '#000000',
            fill: '#D6D6D6',
        },
        outsource: {
            stroke: '#444444',
            fill: '#444444',
        },
    },
    note: {
        evolvedTextColor: '',
        textColor: 'black',
        fontWeight: 'bold',
    },
    attitudes: {
        strokeWidth: '5px',
        fontSize: '14px',
        pioneers: {
            stroke: '#3490dd',
            fill: '#3ccaf8',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        settlers: {
            stroke: '#396dc0',
            fill: '#599afa',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        townplanners: {
            stroke: '#4768c8',
            fill: '#936ff9',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
    },
});

export const Wardley = mergeIntoDefault({
    className: 'wardley',
    fontFamily: 'Consolas, Lucida Console, monospace',
    stroke: 'black',
    pipelineArrowStroke: 'black',
    evolutionSeparationStroke: '#b8b8b8',
    component: {
        fill: 'white',
        stroke: 'black',
        evolved: 'red',
        evolvedFill: 'white',
        strokeWidth: 1,
        pipelineStrokeWidth: 1,
        radius: 5,
        evolvedTextColor: 'red',
        textColor: 'black',
        fontWeight: '500',
        fontSize: '12px',
    },
    annotation: {
        stroke: '#595959',
        strokeWidth: 2,
        fill: 'white',
        boxStroke: '#595959',
        boxStrokeWidth: 1,
        boxFill: '#FFFFFF',
        boxTextColour: 'black',
        text: '',
    },
    methods: {
        buy: {
            stroke: '#D6D6D6',
            fill: '#AAA5A9',
        },
        build: {
            stroke: '#000000',
            fill: '#D6D6D6',
        },
        outsource: {
            stroke: '#444444',
            fill: '#444444',
        },
    },
    note: {
        evolvedTextColor: 'red',
        textColor: 'black',
        fontWeight: 'bold',
    },
    attitudes: {
        strokeWidth: '5px',
        fontSize: '14px',
        pioneers: {
            stroke: '#3490dd',
            fill: '#3ccaf8',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        settlers: {
            stroke: '#396dc0',
            fill: '#599afa',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        townplanners: {
            stroke: '#4768c8',
            fill: '#936ff9',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
    },
});

export const Dark = mergeIntoDefault({
    className: 'dark',
    containerBackground: '#353347',
    fontFamily: '"Helvetica Neue",Helvetica,Arial,sans-serif',
    fontSize: '13px',
    stroke: 'white',
    pipelineArrowStroke: 'white',
    evolutionSeparationStroke: 'white',
    mapGridTextColor: 'rgba(255,255,255,.8)',
    pipelineArrowHeight: 5,
    pipelineArrowWidth: 5,
    strokeWidth: 1,
    strokeDasharray: '2,2',
    anchor: {
        fontSize: '14px',
    },
    attitudes: {
        strokeWidth: '5px',
        fontSize: '14px',
        pioneers: {
            stroke: '#3490dd',
            fill: '#3ccaf8',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        settlers: {
            stroke: '#396dc0',
            fill: '#599afa',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        townplanners: {
            stroke: '#4768c8',
            fill: '#936ff9',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
    },
    methods: {
        buy: {
            stroke: '#D6D6D6',
            fill: '#AAA5A9',
        },
        build: {
            stroke: '#000000',
            fill: '#D6D6D6',
        },
        outsource: {
            stroke: '#444444',
            fill: '#444444',
        },
    },
    market: {
        stroke: '#90caf9',
        fill: 'white',
    },
    component: {
        fontSize: '13px',
        fill: 'rgba(255,255,255,.8)',
        stroke: 'white',
        evolved: '#90caf9',
        evolvedFill: 'white',
        strokeWidth: 1,
        pipelineStrokeWidth: 1,
        radius: 5,
        textColor: 'rgba(255,255,255,.8)',
        textOffset: 8,
        evolvedTextColor: '#90caf9',
        fontWeight: '500',
    },
    submap: {
        fontSize: '13px',
        fill: 'white',
        stroke: 'white',
        evolved: '#90caf9',
        evolvedFill: 'white',
        strokeWidth: 1,
        pipelineStrokeWidth: 1,
        radius: 5,
        textColor: 'white',
        textOffset: 8,
        evolvedTextColor: '#90caf9',
    },
    link: {
        stroke: 'white',
        strokeWidth: 1,
        evolvedStroke: '#90caf9',
        evolvedStrokeWidth: 1,
        flow: '#99c5ee9e',
        flowStrokeWidth: 10,
        flowText: '#03a9f4',
    },
    fluidLink: {
        stroke: 'white',
        strokeDasharray: '2,2',
        strokeWidth: 2,
    },
    annotation: {
        stroke: '#595959',
        strokeWidth: 2,
        fill: 'rgba(255,255,255,.8)',
        text: 'black',
        boxStroke: '#595959',
        boxStrokeWidth: 1,
        boxFill: 'rgba(255,255,255,.8)',
        boxTextColour: 'black',
    },
    note: {
        fontWeight: 'bold',
        fontSize: '12px',
        textColor: 'rgba(255,255,255,.8)',
        evolvedTextColor: 'red',
    },
});

export const Colour = mergeIntoDefault({
    className: 'colour',
    stroke: '#c23667',
    pipelineArrowStroke: '#8cb358',
    evolutionSeparationStroke: '#b8b8b8',
    strokeWidth: 3,
    component: {
        fill: 'white',
        stroke: '#8cb358',
        evolved: '#ea7f5b',
        evolvedFill: 'white',
        strokeWidth: 2,
        pipelineStrokeWidth: 1,
        radius: 7,
        textColor: '#486b1a',
        textOffset: 8,
        evolvedTextColor: '#ea7f5b',
        fontWeight: '500',
    },
    submap: {
        fill: '#8cb358',
        stroke: '#8cb358',
        evolved: '#ea7f5b',
        evolvedFill: '#8cb358',
        strokeWidth: 2,
        pipelineStrokeWidth: 1,
        radius: 7,
        textColor: '#486b1a',
        textOffset: 8,
        evolvedTextColor: '#ea7f5b',
    },
    link: {
        stroke: '#5c5c5c',
        evolvedStroke: '#ea7f5b',
        flow: '#99c5ee9e',
    },
    annotation: {
        stroke: '#015fa5',
        strokeWidth: 2,
        fill: '#99c5ee',
        boxStroke: '#015fa5',
        boxStrokeWidth: 2,
        boxFill: '#99c5ee',
        boxTextColour: 'black',
        text: '',
    },
    methods: {
        buy: {
            stroke: '#D6D6D6',
            fill: '#AAA5A9',
        },
        build: {
            stroke: '#000000',
            fill: '#D6D6D6',
        },
        outsource: {
            stroke: '#444444',
            fill: '#444444',
        },
    },
    note: {
        evolvedTextColor: 'red',
        textColor: 'black',
        fontWeight: 'bold',
    },
    attitudes: {
        strokeWidth: '5px',
        fontSize: '14px',
        pioneers: {
            stroke: '#3490dd',
            fill: '#3ccaf8',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        settlers: {
            stroke: '#396dc0',
            fill: '#599afa',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
        townplanners: {
            stroke: '#4768c8',
            fill: '#936ff9',
            fillOpacity: 0.4,
            strokeOpacity: 0.7,
        },
    },
});

export const Octo = mergeIntoDefault({
    className: 'octo',
    containerBackground: 'white',
    fontFamily: '"Helvetica Neue",Helvetica,Arial,sans-serif',
    fontSize: '13px',
    stroke: '#0E2356',
    pipelineArrowStroke: '#0E2356',
    evolutionSeparationStroke: '#B7BDCC',
    mapGridTextColor: '#0E2356',
    pipelineArrowHeight: 5,
    pipelineArrowWidth: 5,
    strokeWidth: 2,
    strokeDasharray: '2,2',
    anchor: {
        fontSize: '14px',
    },
    attitudes: {
        strokeWidth: '5px',
        fontSize: '14px',
        pioneers: {
            stroke: '#00D2DD',
            fill: '#8AE4EB',
            fillOpacity: 0.4,
            strokeOpacity: 0.8,
        },
        settlers: {
            stroke: '#3E4F78',
            fill: '#6E7B9A',
            fillOpacity: 0.4,
            strokeOpacity: 0.8,
        },
        townplanners: {
            stroke: '#0E2356',
            fill: '#586586',
            fillOpacity: 0.4,
            strokeOpacity: 0.8,
        },
    },
    methods: {
        buy: {
            stroke: '#9FA7BB',
            fill: '#CFD3DD',
        },
        build: {
            stroke: '#0E2356',
            fill: '#E7E9EE',
        },
        outsource: {
            stroke: '#3E4F78',
            fill: '#B7BDCC',
        },
    },
    market: {
        stroke: '#00D2DD',
        fill: 'white',
    },
    component: {
        fontSize: '13px',
        fill: 'white',
        stroke: '#0E2356',
        evolved: '#00D2DD',
        evolvedFill: 'white',
        strokeWidth: 2,
        pipelineStrokeWidth: 2,
        radius: 5,
        textColor: '#0E2356',
        textOffset: 8,
        evolvedTextColor: '#00D2DD',
        fontWeight: '500',
    },
    submap: {
        fontSize: '13px',
        fill: '#0E2356',
        stroke: '#0E2356',
        evolved: '#00D2DD',
        evolvedFill: '#0E2356',
        strokeWidth: 2,
        pipelineStrokeWidth: 2,
        radius: 5,
        textColor: '#0E2356',
        textOffset: 8,
        evolvedTextColor: '#00D2DD',
    },
    link: {
        stroke: '#6E7B9A',
        strokeWidth: 1,
        evolvedStroke: '#00D2DD',
        evolvedStrokeWidth: 2,
        flow: '#8AE4EB',
        flowStrokeWidth: 10,
        flowText: '#00D2DD',
        contextFontSize: '11px',
    },
    fluidLink: {
        stroke: '#6E7B9A',
        strokeDasharray: '2,2',
        strokeWidth: 2,
    },
    annotation: {
        stroke: '#0E2356',
        strokeWidth: 2,
        fill: '#E7E9EE',
        text: '#0E2356',
        boxStroke: '#00D2DD',
        boxStrokeWidth: 2,
        boxFill: 'white',
        boxTextColour: '#0E2356',
    },
    note: {
        fontWeight: 'bold',
        fontSize: '12px',
        textColor: '#0E2356',
        evolvedTextColor: '#00D2DD',
    },
});
